import { z } from "zod";

const FieldVisibilityType = z.enum(["details-only", "hidden", "normal", "retired", "sensitive"]);

export const FieldValuesType = z.enum(["list", "search", "none", "auto-list"]);

export const FieldBaseType = z.enum([
  "type/*",
  "type/field-values-unsupported",
  "type/fingerprint-unsupported",
  "type/Large",
  "type/Number",
  "type/Integer",
  "type/BigInteger",
  "type/Float",
  "type/Decimal",
  "type/Text",
  "type/UUID",
  "type/OracleCLOB",
  "type/Temporal",
  "type/HasDate",
  "type/HasTime",
  "type/Date",
  "type/Time",
  "type/TimeWithTZ",
  "type/TimeWithLocalTZ",
  "type/TimeWithZoneOffset",
  "type/DateTime",
  "type/DateTimeWithTZ",
  "type/DateTimeWithLocalTZ",
  "type/DateTimeWithZoneOffset",
  "type/DateTimeWithZoneID",
  "type/Instant",
  "type/Interval",
  "type/Boolean",
  "type/DruidHyperUnique",
  "type/SnowflakeVariant",
  "type/TextLike",
  "type/MongoBSONID",
  "type/MongoBinData",
  "type/MySQLEnum",
  "type/PostgresEnum",
  "type/PostgresBitString",
  "type/IPAddress",
  "type/Collection",
  "type/Dictionary",
  "type/Array",
  "type/Structured",
  "type/JSON",
  "type/DruidJSON",
  "type/XML",
]);
export type FieldBaseType = z.infer<typeof FieldBaseType>;

export const FieldSemanticType = z.enum([
  "type/Quantity",
  "type/Share",
  "type/Percentage",
  "type/Currency",
  "type/Income",
  "type/Discount",
  "type/Price",
  "type/GrossMargin",
  "type/Cost",
  "type/Score",
  "type/Duration",
  "type/Location",
  "type/Coordinate",
  "type/Latitude",
  "type/Longitude",
  "type/Address",
  "type/City",
  "type/State",
  "type/Country",
  "type/ZipCode",
  "type/URL",
  "type/ImageURL",
  "type/AvatarURL",
  "type/Email",
  "type/Description",
  "type/Comment",
  "type/IPAddress",
  "type/Category",
  "type/Enum",
  "type/Name",
  "type/Title",
  "type/Product",
  "type/Company",
  "type/Subscription",
  "type/Source",
  "type/CreationTemporal",
  "type/CreationTimestamp",
  "type/CreationTime",
  "type/CreationDate",
  "type/JoinTemporal",
  "type/JoinTimestamp",
  "type/JoinTime",
  "type/JoinDate",
  "type/CancelationTemporal",
  "type/CancelationTimestamp",
  "type/CancelationTime",
  "type/CancelationDate",
  "type/DeletionTemporal",
  "type/DeletionTimestamp",
  "type/DeletionTime",
  "type/DeletionDate",
  "type/UpdatedTemporal",
  "type/UpdatedTimestamp",
  "type/UpdatedTime",
  "type/UpdatedDate",
  "type/Birthdate",
  "type/Structured",
  "type/SerializedJSON",
  "type/JSON",
  "type/DruidJSON",
  "type/XML",
  "type/User",
  "type/Author",
  "type/Owner",
  "type/FK",
  "type/PK",
]);
export type FieldSemanticType = z.infer<typeof FieldSemanticType>;

export const Field = z
  .object({
    id: z.number().int(),
    table_id: z.number().int(),
    name: z.string(),
    display_name: z.string(),
    description: z.string().nullable(),
    database_type: z.string().nullable().optional(),
    base_type: FieldBaseType,
    semantic_type: FieldSemanticType.nullable(),
    fk_target_field_id: z.number().int().nullable(),
    has_field_values: FieldValuesType.nullable().optional(),
    visibility_type: FieldVisibilityType.nullable().optional(),
    active: z.boolean().optional(),
    position: z.number().int().optional(),
  })
  .loose();
export type Field = z.infer<typeof Field>;

export const FieldCompact = Field.pick({
  id: true,
  name: true,
  display_name: true,
  description: true,
  table_id: true,
  base_type: true,
  semantic_type: true,
  fk_target_field_id: true,
}).strip();
export type FieldCompact = z.infer<typeof FieldCompact>;

export const FieldValues = z
  .object({
    values: z.array(z.array(z.unknown())),
    field_id: z.number().int().optional(),
    has_more_values: z.boolean().optional(),
    has_field_values: FieldValuesType.optional(),
  })
  .loose();
export type FieldValues = z.infer<typeof FieldValues>;

export const FieldValuesCompact = FieldValues.pick({
  values: true,
  field_id: true,
  has_more_values: true,
}).strip();
export type FieldValuesCompact = z.infer<typeof FieldValuesCompact>;
