import type { SessionEvent, SessionEventType } from "./events";

const SESSION_ID = "ses_7c1f";
const TURN_ID = "trn_04";
const AT = "2026-09-22T12:00:00.000Z";

export const SESSION_EVENT_FIXTURES: Readonly<Record<SessionEventType, SessionEvent>> = {
  "session.created": {
    type: "session.created",
    id: "evt_001",
    sessionId: SESSION_ID,
    seq: 1,
    at: AT,
    title: "Clean the orders table",
    provider: "claude",
    model: "claude-opus-4",
    workspace: { kind: "worktree", path: "/repo/.rde/orders", branch: "rde/orders", base: "main" },
    permissionMode: "ask",
  },
  "session.updated": {
    type: "session.updated",
    id: "evt_002",
    sessionId: SESSION_ID,
    seq: 2,
    at: AT,
    changes: { nativeSessionId: "9f2c1c1e-6a2f-4f1a-9a0c-0d3b7f2a5e11", model: "claude-opus-4" },
  },
  "session.failed": {
    type: "session.failed",
    id: "evt_003",
    sessionId: SESSION_ID,
    seq: 3,
    at: AT,
    reason: "the agent process exited before the turn started",
    providerError: "spawn claude ENOENT",
  },
  "session.rewound": {
    type: "session.rewound",
    id: "evt_017",
    sessionId: SESSION_ID,
    seq: 17,
    at: AT,
    turnId: TURN_ID,
    conversation: { kind: "replayed", replay: "User:\nClean the orders table" },
    filesRestored: true,
    checkpointRef: "refs/rde/checkpoints/ses_7c1f/2",
  },
  "sync.completed": {
    type: "sync.completed",
    id: "evt_004",
    sessionId: SESSION_ID,
    seq: 4,
    at: AT,
    branch: "rde/orders",
    outcome: { kind: "imported", links: [] },
  },
  "turn.started": {
    type: "turn.started",
    id: "evt_005",
    sessionId: SESSION_ID,
    seq: 5,
    at: AT,
    turnId: TURN_ID,
    userMessageId: "msg_01",
  },
  "user.message": {
    type: "user.message",
    id: "evt_006",
    sessionId: SESSION_ID,
    seq: 6,
    at: AT,
    turnId: TURN_ID,
    messageId: "msg_01",
    text: "Add a transform test for orders_clean.",
    attachments: ["transforms/orders_clean.yaml"],
  },
  "assistant.reasoning": {
    type: "assistant.reasoning",
    id: "evt_007",
    sessionId: SESSION_ID,
    seq: 7,
    at: AT,
    turnId: TURN_ID,
    messageId: "msg_02",
    chunk: { kind: "delta", text: "The transform writes to orders_clean, so the test asserts" },
  },
  "assistant.text": {
    type: "assistant.text",
    id: "evt_008",
    sessionId: SESSION_ID,
    seq: 8,
    at: AT,
    turnId: TURN_ID,
    messageId: "msg_03",
    chunk: { kind: "complete", text: "I added the test and ran it." },
  },
  "tool.started": {
    type: "tool.started",
    id: "evt_009",
    sessionId: SESSION_ID,
    seq: 9,
    at: AT,
    turnId: TURN_ID,
    callId: "toolu_01",
    tool: "edit",
    label: "Write transform-tests/orders_clean.yaml",
    input: { file_path: "transform-tests/orders_clean.yaml", content: "name: orders_clean\n" },
  },
  "tool.updated": {
    type: "tool.updated",
    id: "evt_010",
    sessionId: SESSION_ID,
    seq: 10,
    at: AT,
    turnId: TURN_ID,
    callId: "toolu_01",
    progress: { kind: "output", text: "1 test, 1 passed\n" },
  },
  "tool.completed": {
    type: "tool.completed",
    id: "evt_011",
    sessionId: SESSION_ID,
    seq: 11,
    at: AT,
    turnId: TURN_ID,
    callId: "toolu_01",
    status: "ok",
    output: "File created successfully.",
    files: ["transform-tests/orders_clean.yaml"],
    patch: "@@ -0,0 +1 @@\n+name: orders_clean\n",
  },
  "request.opened": {
    type: "request.opened",
    id: "evt_012",
    sessionId: SESSION_ID,
    seq: 12,
    at: AT,
    turnId: TURN_ID,
    requestId: "req_01",
    kind: "permission",
    callId: "toolu_01",
    prompt: "Write transform-tests/orders_clean.yaml?",
    options: [
      { id: "allow", label: "Allow once", hint: null },
      { id: "allow-always", label: "Allow every write in this session", hint: null },
      { id: "deny", label: "Deny", hint: "The agent is told the write was refused" },
    ],
    acceptsText: false,
  },
  "request.resolved": {
    type: "request.resolved",
    id: "evt_013",
    sessionId: SESSION_ID,
    seq: 13,
    at: AT,
    turnId: TURN_ID,
    requestId: "req_01",
    resolution: { kind: "answered", optionId: "allow", text: null },
  },
  "context.compacted": {
    type: "context.compacted",
    id: "evt_014",
    sessionId: SESSION_ID,
    seq: 14,
    at: AT,
    turnId: TURN_ID,
    notice: "The conversation was summarised to free context.",
  },
  "turn.completed": {
    type: "turn.completed",
    id: "evt_015",
    sessionId: SESSION_ID,
    seq: 15,
    at: AT,
    turnId: TURN_ID,
    outcome: { kind: "completed" },
    usage: {
      inputTokens: 1842,
      outputTokens: 311,
      cacheReadTokens: 10234,
      cacheWriteTokens: 0,
      costUsd: 0.0412,
    },
    durationMs: 8731,
  },
  "checkpoint.captured": {
    type: "checkpoint.captured",
    id: "evt_016",
    sessionId: SESSION_ID,
    seq: 16,
    at: AT,
    turnId: TURN_ID,
    ref: "refs/rde/checkpoints/ses_7c1f/1",
    files: [{ path: "transform-tests/orders_clean.yaml", added: 12, removed: 0 }],
  },
};
