import type { FeatureName } from "./features";

// Keyed `<resource>.<method>` as the method is reached on the client, so a key reads the same in a
// command, a skill and an error. An empty list is a promise that every supported server answers. A
// list is ordered strictest-first: the first feature the server lacks is the one the refusal names,
// and naming the lowest floor would send a user through one upgrade only to be refused again.
export const METHOD_REQUIREMENTS = {
  "card.list": [],
  "card.get": [],
  "card.create": [],
  "card.update": [],
  "card.archive": [],
  "card.query": [],
  "card.exportQuery": [],
  "collection.list": [],
  "collection.listWithLibrary": [],
  "collection.get": [],
  "collection.create": [],
  "collection.update": [],
  "collection.archive": [],
  "collection.itemPages": [],
  "collection.tree": [],
  "contentTranslation.download": ["contentTranslation"],
  "contentTranslation.upload": ["contentTranslation"],
  "dashboard.list": [],
  "dashboard.get": [],
  "dashboard.create": [],
  "dashboard.update": [],
  "dashboard.archive": [],
  "dashboard.updateDashcard": [],
  "dashboard.checkCardReferences": [],
  "dashboard.parameterValues": [],
  "dashboard.searchParameterValues": [],
  "database.list": [],
  "database.get": [],
  "database.schemas": [],
  "database.schemaTables": [],
  "database.syncSchema": [],
  "database.rescanValues": [],
  "dataset.query": [],
  "dataset.native": [],
  "dataset.queryMetadata": [],
  "dataset.exportQuery": [],
  "dependency.breakingPages": ["dependencyItemListings"],
  "dependency.broken": ["dependencyItemListings"],
  "dependency.dependents": ["dependencyItemListings"],
  "dependency.graph": ["dependencyGraph"],
  "dependency.unreferencedPages": ["dependencyItemListings"],
  "document.list": [],
  "document.get": [],
  "document.create": [],
  "document.update": [],
  "document.archive": [],
  "eidTranslation.translate": [],
  "erd.get": ["erd"],
  "field.get": [],
  "field.update": [],
  "field.setDataSensitivity": ["fieldDataSensitivity"],
  "field.search": [],
  "field.remapping": [],
  "field.summary": [],
  "field.values": [],
  "gitSync.currentTask": ["remoteSync"],
  "gitSync.cancelTask": ["remoteSync"],
  "gitSync.isDirty": ["remoteSync"],
  "gitSync.dirty": ["remoteSync"],
  "gitSync.hasRemoteChanges": ["remoteSync"],
  "gitSync.import": ["remoteSync"],
  "gitSync.export": ["remoteSync"],
  "gitSync.exportPreflight": ["remoteSyncExportPreflight"],
  "gitSync.stash": ["remoteSync"],
  "gitSync.branches": ["remoteSync"],
  "gitSync.createBranch": ["remoteSync"],
  "gitSync.setCollectionSynced": ["remoteSync"],
  "gitSync.syncedCollections": ["remoteSync"],
  "gitSync.remoteUrl": [],
  "gitSync.branch": [],
  "gitSync.waitForTask": ["remoteSync"],
  "glossary.list": [],
  "glossary.create": [],
  "glossary.update": [],
  "glossary.delete": [],
  "library.get": ["library"],
  "library.create": ["library"],
  "library.ensureDataCollectionId": ["library"],
  "library.publishTables": ["library"],
  "library.unpublishTables": ["library"],
  "measure.list": ["measures"],
  "measure.get": ["measures"],
  "measure.create": ["measures"],
  "measure.update": ["measures"],
  "measure.archive": ["measures"],
  "moderationReview.create": ["contentVerification"],
  "notification.list": [],
  "notification.get": [],
  "notification.create": [],
  "notification.update": [],
  "notification.archive": [],
  "notification.send": [],
  "pulse.list": [],
  "pulse.get": [],
  "pulse.create": [],
  "pulse.update": [],
  "pulse.archive": [],
  "revision.list": [],
  "revision.revert": [],
  "search.query": [],
  "segment.list": [],
  "segment.get": [],
  "segment.create": [],
  "segment.update": [],
  "segment.archive": [],
  "setting.list": [],
  "setting.get": [],
  "setting.set": [],
  "setup.create": [],
  "snippet.list": [],
  "snippet.get": [],
  "snippet.create": [],
  "snippet.update": [],
  "snippet.archive": [],
  "table.list": [],
  "table.get": [],
  "table.update": [],
  "table.queryMetadata": [],
  "table.fks": [],
  "table.syncSchema": [],
  "table.rescanValues": [],
  "table.bulkEdit": ["bulkTableEdit"],
  "table.appendCsv": [],
  "table.replaceCsv": [],
  "timeline.list": [],
  "timeline.get": [],
  "timeline.events": [],
  "timeline.create": [],
  "timeline.update": [],
  "timeline.archive": [],
  "timeline.delete": [],
  "timelineEvent.get": [],
  "timelineEvent.create": [],
  "timelineEvent.update": [],
  "timelineEvent.archive": [],
  "timelineEvent.delete": [],
  "transform.list": ["transforms"],
  "transform.get": ["transforms"],
  "transform.create": ["transforms"],
  "transform.update": ["transforms"],
  "transform.delete": ["transforms"],
  "transform.deleteTable": ["transforms"],
  "transform.dependencies": ["transforms"],
  "transform.cancel": ["transforms"],
  "transform.getRun": ["transforms"],
  "transform.runPages": ["transforms"],
  "transform.run": ["transforms"],
  "transformJob.list": ["transforms"],
  "transformJob.get": ["transforms"],
  "transformJob.create": ["transforms"],
  "transformJob.update": ["transforms"],
  "transformJob.delete": ["transforms"],
  "transformJob.run": ["transforms"],
  "transformJob.transforms": ["transforms"],
  "transformJob.setActive": ["transformJobActivation", "transforms"],
  "transformTag.list": ["transforms"],
  "transformTag.create": ["transforms"],
  "transformTag.update": ["transforms"],
  "transformTag.delete": ["transforms"],
  "upload.createFromCsv": [],
  "user.current": [],
} satisfies Record<string, readonly FeatureName[]>;

export type MethodKey = keyof typeof METHOD_REQUIREMENTS;

export function isMethodKey(key: string): key is MethodKey {
  return Object.hasOwn(METHOD_REQUIREMENTS, key);
}

export const METHOD_KEYS: ReadonlyArray<MethodKey> =
  Object.keys(METHOD_REQUIREMENTS).filter(isMethodKey);

export function methodRequirements(key: MethodKey): readonly FeatureName[] {
  return METHOD_REQUIREMENTS[key];
}
